/**
 * src/audio/sounds.ts
 *
 * SoundManager: a tiny, self-contained SFX layer for the game's juice
 * (haptics + sound fire together — see src/controller/haptics.ts for the
 * haptic side of the same events). Every WAV is procedurally generated by
 * tools/gen-sounds.js into assets/sounds/ — no external audio assets.
 *
 * Design constraints (per the audio task):
 *  - `play(name)` is fire-and-forget and MUST NEVER throw — a missing/broken
 *    sound must never break gameplay. Every native call is wrapped in
 *    try/catch and callers never need to await or catch anything.
 *  - Overlap-safe: each sound gets a small round-robin pool of AudioPlayer
 *    instances (instead of one shared player) so two triggers in quick
 *    succession (e.g. two rapid 'move's) don't cut each other off.
 *  - Mute preference persists in AsyncStorage (`train_sound_muted`),
 *    default UNMUTED, mirroring the pattern used by
 *    src/controller/tutorial.ts's `train_tutorial_done` flag.
 */
import { createAudioPlayer, setAudioModeAsync, type AudioPlayer } from 'expo-audio';
import AsyncStorage from '@react-native-async-storage/async-storage';

export type SoundName = 'select' | 'place' | 'move' | 'reject' | 'push' | 'win' | 'star';

const MUTE_STORAGE_KEY = 'train_sound_muted';
/** How many overlapping instances of the SAME sound we keep ready. */
const POOL_SIZE = 3;

// require() of a local media asset resolves to a Metro asset module id at
// bundle time (same mechanism used for images) — expo-audio's AudioSource
// accepts that id directly, exactly like `useAudioPlayer(require('./x.mp3'))`
// in the expo-audio docs.
const SOUND_SOURCES: Record<SoundName, number> = {
  select: require('../../assets/sounds/select.wav'),
  place: require('../../assets/sounds/place.wav'),
  move: require('../../assets/sounds/move.wav'),
  reject: require('../../assets/sounds/reject.wav'),
  push: require('../../assets/sounds/push.wav'),
  win: require('../../assets/sounds/win.wav'),
  star: require('../../assets/sounds/star.wav'),
};

let muted = false;
let initPromise: Promise<void> | null = null;
const pools: Partial<Record<SoundName, AudioPlayer[]>> = {};
const poolCursor: Partial<Record<SoundName, number>> = {};
/** Listeners notified whenever the mute flag changes (drives the HUD toggle icon). */
const listeners = new Set<(muted: boolean) => void>();

function notifyListeners(): void {
  for (const l of listeners) {
    try {
      l(muted);
    } catch {
      // a bad listener must not break the others
    }
  }
}

/**
 * Loads the persisted mute preference and preloads a small player pool per
 * sound. Safe to call multiple times (subsequent calls reuse the same
 * in-flight/completed promise). Never throws — worst case, sounds simply
 * won't play and the game continues normally.
 */
function init(): Promise<void> {
  if (initPromise) return initPromise;
  initPromise = (async () => {
    try {
      const stored = await AsyncStorage.getItem(MUTE_STORAGE_KEY);
      muted = stored === '1';
    } catch {
      muted = false;
    }

    try {
      // Sound effects should mix with any other audio on the device rather
      // than stealing focus, and still play with the ringer switched to
      // silent (common on phones) since these are UI/game feedback, not
      // music — see expo-audio's `interruptionMode` doc: 'mixWithOthers'
      // is "best suited for sound effects, UI feedback, or short audio
      // clips."
      await setAudioModeAsync({
        playsInSilentMode: true,
        shouldPlayInBackground: false,
        interruptionMode: 'mixWithOthers',
      });
    } catch {
      // Audio mode is a nicety, not a requirement — keep going regardless.
    }

    try {
      (Object.keys(SOUND_SOURCES) as SoundName[]).forEach((name) => {
        const players: AudioPlayer[] = [];
        for (let i = 0; i < POOL_SIZE; i++) {
          players.push(createAudioPlayer(SOUND_SOURCES[name]));
        }
        pools[name] = players;
        poolCursor[name] = 0;
      });
    } catch {
      // Preload failed (e.g. platform without audio support) — `play()`
      // below already guards on missing pools, so this is a silent no-op.
    }

    notifyListeners();
  })().catch(() => {
    // init() itself must never reject.
  });
  return initPromise;
}

/**
 * Plays `name` immediately if unmuted. Fire-and-forget: does not return a
 * promise, never throws, and is safe to call before `init()` resolves (it's
 * simply a no-op until the pools are ready).
 */
function play(name: SoundName): void {
  if (muted) return;
  try {
    const players = pools[name];
    if (!players || players.length === 0) return;
    const cursor = poolCursor[name] ?? 0;
    poolCursor[name] = (cursor + 1) % players.length;
    const p = players[cursor];
    // Rewind then play so a pool slot that's mid-playback from a previous
    // trigger restarts cleanly rather than silently no-op'ing.
    void p.seekTo(0).catch(() => {});
    p.play();
  } catch {
    // Sound is cosmetic — never let a native audio hiccup break gameplay.
  }
}

function isMuted(): boolean {
  return muted;
}

/** Sets the mute flag and persists it. Never throws. */
async function setMuted(value: boolean): Promise<void> {
  muted = value;
  notifyListeners();
  try {
    await AsyncStorage.setItem(MUTE_STORAGE_KEY, value ? '1' : '0');
  } catch {
    // Best-effort persistence — the in-memory flag above still applies for
    // the rest of this session even if writing to disk fails.
  }
}

/** Subscribes to mute-state changes (e.g. to sync a HUD toggle icon). Returns an unsubscribe function. */
function onMuteChange(listener: (muted: boolean) => void): () => void {
  listeners.add(listener);
  return () => listeners.delete(listener);
}

export const SoundManager = { init, play, isMuted, setMuted, onMuteChange };
